add(ci): add parser to ci

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,7 +6,7 @@ on:
       - master
 
 jobs:
-  build:
+  build-core:
     runs-on: ubuntu-latest
 
     steps:
@@ -31,8 +31,34 @@ jobs:
           exit 1
         fi
 
+  build-parser:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v2
+      with:
+        dotnet-version: '6.0'  # or the version you're using
+
+    - name: Restore dependencies
+      run: dotnet restore ./JSONPatchParser
+
+    - name: Build in Release mode
+      run: dotnet build ./JSONPatchParser --configuration Release
+
+    - name: Check build status
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Build failed!"
+          exit 1
+        fi
+
+
   test:
-    needs: build  # Make sure the build job is completed before running tests
+    needs: [build-core, build-parser]  # Make sure the build job is completed before running tests
     runs-on: ubuntu-latest
 
     steps:
